name: Build dae latest

on:
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target code
        uses: actions/checkout@v4
        with:
          repository: 'olicesx/dae'
          ref: 'latest'
          submodules: 'recursive'

      - name: Build dae in Alpine (musl native)
        uses: addnab/docker-run-action@v3
        with:
          image: golang:alpine
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            apk update
            apk add --no-cache clang llvm make git gcc musl-dev elfutils-dev linux-headers
            git config --global --add safe.directory /work
            make CC=clang GOFLAGS="-buildvcs=false"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dae-linux-x86_64
          path: dae
